### ISSUE TITLE
Hide read?

### ISSUE THREAD

**Issue by username1290** [ksdme/hackerscroll-frontend#1]
Very useful, thanks! 
Just set it as my homepage :)

Question: Is there a way to hide read stories?
Example: I click "Read" in 5 of the 23 stories, then those 5 are hidden, and only see other 18 (23-5)

Thanks

**Comment by ksdme** [comment]
That's a great idea. It should one of the top action buttons with the setting persisted.

**Comment by username1290** [comment]
Cool, it already feels like a _calmer_ version of HN

**Comment by ksdme** [comment]
@sogen You can now hide read stories using "Hide Read Stories" button on the top. It's disabled by default but, if you toggle it once, the setting will be remembered.

Thanks for your feedback!

**Comment by username1290** [comment]
nice, works great! 
and have a Happy New Year!
